sudo: false
language: java
services:
  docker
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
install: true
script: "mvn clean install"
deploy:
  provider: script
  script: sh .travis-support/deploy.sh
  on:
    branch: master
